WITH RECURSIVE URUNAGACI AS (
  SELECT
    CAST(0 AS INTEGER) AS SEVIYE,
    CAST(NULL AS INTEGER) AS STOK_DETAY_NO,
    CAST(NULL AS INTEGER) AS ANA_STOK_VARYANT_NO,
    K.STOK_VARYANT_NO,
    K.STOK_NO,
    CAST(? AS DOUBLE PRECISION) AS MIKTAR, -- SET TO 1,2 ...
    CAST(? AS VARCHAR(10)) AS BIRIM, -- SET TO 'Adet' etc..
    CAST('/0/' AS VARCHAR(1000)) AS TREE_PATH
  FROM STOKKAVA K
  WHERE K.STOK_VARYANT_NO = ? -- SET TO STOK_VARYANT_NO

  UNION ALL
  SELECT
    A.SEVIYE + 1,
    D.STOK_DETAY_NO,
    D.ANA_STOK_VARYANT_NO,
    D.STOK_VARYANT_NO,
    D.STOK_NO,
    D.MIKTAR * A.MIKTAR / COALESCE(NULLIF(V.MIKTAR, 0), 1),
    D.BIRIM,
    A.TREE_PATH || D.STOK_DETAY_NO || '/'
  FROM URUNAGACI A
  INNER JOIN STOKKAVA V ON V.STOK_VARYANT_NO = A.STOK_VARYANT_NO
  INNER JOIN STOKKADE D ON D.ANA_STOK_VARYANT_NO = A.STOK_VARYANT_NO
  WHERE A.SEVIYE < 100
),

ALT_VARYANTLAR AS (
  SELECT DISTINCT ANA_STOK_VARYANT_NO
  FROM STOKKADE
),

MALIYETLI_URUNAGACI AS (
  SELECT
    A.*,
    F.LISTE_FIYATI AS BIRIM_FIYAT,
    A.MIKTAR * F.LISTE_FIYATI AS TUTAR
    FROM URUNAGACI A
    LEFT JOIN ALT_VARYANTLAR AV ON AV.ANA_STOK_VARYANT_NO = A.STOK_VARYANT_NO
    LEFT JOIN FIYADETA F ON F.STOK_NO = A.STOK_NO AND F.TURU = 'Maliyet'
)

SELECT
  A.SEVIYE,
  A.STOK_DETAY_NO,
  A.ANA_STOK_VARYANT_NO,
  A.STOK_VARYANT_NO,
  A.STOK_NO,
  K.STOK_TIP_ADI,
  K.STOK_KODU,
  K.STOK_ADI,
  V.VARYANT_KODU,
  V.VARYANT_ADI,
  D.ACIKLAMA,
  A.MIKTAR,
  A.BIRIM,
  D.MIKTAR1,
  A.BIRIM_FIYAT,
  A.TUTAR,
  (
    SELECT SUM(COALESCE(AA.TUTAR, 0))
    FROM MALIYETLI_URUNAGACI AA
    WHERE AA.TREE_PATH LIKE A.TREE_PATH || '%'
  ) AS ANA_MALIYET,
  A.TREE_PATH
FROM MALIYETLI_URUNAGACI A
JOIN STOKKART K ON K.STOK_NO = A.STOK_NO
LEFT JOIN STOKKAVA V ON V.STOK_VARYANT_NO = A.STOK_VARYANT_NO
LEFT JOIN STOKKADE D ON D.STOK_DETAY_NO = A.STOK_DETAY_NO
ORDER BY A.TREE_PATH;
